# Project Parameters

# Model Parameters
first_conv_in: 1
first_conv_out: 5
first_conv_kernel: 5
second_conv_out: 50
second_conv_kernel: 5
first_fc_output: 100
second_fc_output: 10
batch_size: 64
savedModelDir: './trained_models/'
testModelPath: './trained_models/'

# Dataset Parameters
datasetDir: './data/'
num_workers: 2

# Training Parameters
trainModel: True
useGPU: False
resumeTraining: False
num_epochs: 50
max_norm: 400
# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-2
momentum: 0.9
nesterov: True
update_frequency: 2
