# Project Parameters

# Model Parameters
image_size: [28, 28]
hidden_size: 16
output_size: 10
batch_size: 32
savedModelDir: './trained_models/'
testModelPath: './trained_models/Trained_Model'

# Dataset Parameters
datasetDir: './data/'
num_workers: 2

# Training Parameters
trainModel: False
useGPU: False
resumeTraining: False
num_epochs: 1000
max_norm: 400
# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-2
momentum: 0.9
nesterov: True
update_frequency: 2
