# Project Parameters

# Model Parameters
batch_size: 128
savedModelDir: './trained_models/'
testModelPath: './trained_models/Trained_Model_2000_Episodes'

# Replay Memory Parameters
replayMemoryCapacity: 10000

# Training Parameters
trainModel: False
useGPU: False
resumeTraining: False
num_episodes: 10000
num_steps_per_episode: 1000
gamma: 0.999
target_update: 50

# Epsilon Greedy Policy Parameters
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 500

# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-3
momentum: 0.9
nesterov: True

# Scheduler Parameters
decay_coeff: 0.5
step_size: 1000
