# Project Parameters

# Model Parameters
image_size: [32, 32]
conv1_in_size: 3
conv1_out_size: 64
conv2_out_size: 128
conv3_out_size: 256
conv4_out_size: 512
fc1_out_size: 1024
fc2_out_size: 256
output_size: 10
batch_size: 16
savedModelDir: './trained_models/'
testModelPath: './trained_models/Trained_Model_86_Accuracy'

# Dataset Parameters
datasetDir: './data/'
num_workers: 2

# Training Parameters
trainModel: False
useGPU: False
resumeTraining: False
num_epochs: 50
max_norm: 400
# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-2
momentum: 0.9
nesterov: True
update_frequency: 2