# Project Parameters

# Model Parameters
batch_size: 64
savedModelDir: './trained_models/'
testModelPath: './trained_models/Trained_Model_900_Episodes'

# Replay Memory Parameters
replayMemoryCapacity: 30000

# Training Parameters
trainModel: False
useGPU: False
resumeTraining: False
num_episodes: 1000
num_steps_per_episode: 1000
max_grad_val: 1
gamma: 0.99
target_update: 100

# Epsilon Greedy Policy Parameters
epsilon_start: 0.9
epsilon_end: 0.05
epsilon_decay: 400

# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-3
momentum: 0.9
nesterov: True

# SVRG Parameters
update_frequency: 2

# Scheduler Parameters
decay_coeff: 0.5
step_size: 300
